### ISSUE TITLE
[PWA] Add share link button on the MapView

### ISSUE THREAD

**Issue by inishchith** [inishchith/MeetInTheMiddle#16]
**`Description`**: 
- The website can be viewed as a PWA on smaller devices which makes it convenient to use, but it looses out the address bar, thus disabling the sharing of link for the common mapView with other people.

**`Idea`**:
- To add a share icon on the MapView, which can be used to share the link.
- Shouldn't be a distraction.

> Once this is done, we can officially make a switch to the PWA [[branch](https://github.com/inishchith/MeetInTheMiddle/tree/PWA-develop)]

**Comment by singhvisha** [comment]
hi @inishchith,
I would like to work on it.

**Comment by inishchith** [comment]
@singhvisha Sure, Go ahead!

**Comment by Hritik14** [comment]
A share link could be placed in the following box.
![image](https://user-images.githubusercontent.com/7457065/70629757-7db1ff00-1c50-11ea-9246-552495ae6070.png)
