### ISSUE TITLE
[Home] Redesign home page

### ISSUE THREAD

**Issue by inishchith** [inishchith/MeetInTheMiddle#18]
**`Description`**:
- As the current home page contains an Image and the input boxes are on the left side, I feel there's a need to redesign the current version to something simple

**`Ideas`**:
- No background Image
- Use simplistic color scheme (eg, white background and a center input box)

> feel free to share ideas/mocks

**Comment by Hritik14** [comment]
How about something as simple as Google home page ?

**Comment by inishchith** [comment]
Hi @Hritik14,
Feel free to work on it if you're interested.
