### ISSUE TITLE
Meeting pointnot reachable

### ISSUE THREAD

**Issue by yash-gupta01** [inishchith/MeetInTheMiddle#19]

**Comment by inishchith** [comment]
@evilshipper Please add specifications, I'll look into it.

**Comment by yash-gupta01** [comment]
if the desired location is not reachable via roads then the current meeting point must be taken as a centre and the nearest road reachable point be shown as new meeting point

**Comment by yash-gupta01** [comment]
take for example :
1.Madagascar
2.Delhi 
2.Sydney ..
.
Then you are going to land somewhere in mid ocean
