### ISSUE TITLE
Get current geolocation

### ISSUE THREAD

**Issue by Hritik14** [inishchith/MeetInTheMiddle#20]
There should be a button in the "Enter location" field to automatically detect current location and populate one value.

**Comment by inishchith** [comment]
@Hritik14 Please add a description.

Thanks!

**Comment by Hritik14** [comment]
Updated the post.

**Comment by AdilMah** [comment]
I'll like to go with this.

**Comment by inishchith** [comment]
@AdilMah Sure, Please go ahead :)
