### ISSUE TITLE
Clear/Clear all button not working on firefox

### ISSUE THREAD

**Issue by Hritik14** [inishchith/MeetInTheMiddle#22]
It just reloads the page.
Works fine on Chrome.
Enhancement: Do not reload while removing an item from the list.

**Comment by XLAR-8** [comment]
False-positive, looks fine to me. :P

**Comment by Hritik14** [comment]
The version is FF 71.0. Still reproducible. I'll try to get more logs as soon as possible.

**Comment by ritkat** [comment]
@inishchith I was able to reproduce the issue in Firefox version 70.0.1 on windows 10 I was able to fix this. I still see some inconsistent behavior for clear button but I believe the clear all issue has been fixed. I am attaching the image of app.js. The changes are on line number 402. Please review and let me know if it is good for commit. Could you please setup a new branch for commit as today is the deadline.
<img width="380" alt="appimg" src="https://user-images.githubusercontent.com/58631634/71258181-8e9ef680-235b-11ea-9e76-54f3bdd25165.PNG">

**Comment by inishchith** [comment]
@ritukat Please open a PR for the fix. I'll have a look and merge it right away, if all's good.
