### ISSUE TITLE
Use location coordinates in URL query rather than having a username

### ISSUE THREAD

**Issue by Hritik14** [inishchith/MeetInTheMiddle#23]
I've not yet looked at the code but a username in the query suggests that there is a key value pairing about the username and the added locations.    
I think it would be better to have the coordinates of the locations sent to the server directly to avoid that redundant database.

It would also enable to create long lasting sharing URLs.

**Comment by inishchith** [comment]
> I've not yet looked at the code but a username in the query suggests that there is a key value pairing about the username and the added locations.

Sorry, but no. The username just creates a channel for a group of people, then every location (changes) is communicated to the subscribers.

> It would also enable to create long lasting sharing URLs.

As we're using an external service(PubNub), it claims every channel created lasts until explicitly deleted.
@Hritik14 Please, I would suggest you have a look at the codebase.

Thanks!

**Comment by Hritik14** [comment]
My mistake.
