### ISSUE TITLE
Same location bug

### ISSUE THREAD

**Issue by BraunEduardo** [inishchith/MeetInTheMiddle#6]
It's possible to add same location twice (feature i guess, should keep it), but when removing, it removes all repeated locations keeping just one, rendering the map again for each remove.
The final render shows wrong midway, I think it keeps removed locations somewhere and search for midway with they included.

**Comment by inishchith** [comment]
Thanks for the suggestion, I personally think this addition would be irrelevant. Feel free to get back and reopen if you have some additions related to this ;)
